[package]
name = "modern-cv"
version = "0.2.0"
entrypoint = "src/lib.typ"
authors = ["Claudio Mattera"]
license = "MIT"
description = "A modern CV template with timelines"
homepage = "https://git.claudiomattera.it/claudiomattera/typst-modern-cv"
repository = "https://git.claudiomattera.it/claudiomattera/typst-modern-cv"
keywords = ["cv", "curriculum", "timeline"]
compiler = "0.9.0"
exclude = [
    "Makefile",
    ".drone.yml",
    ".gitignore",
    ".pre-commit-config.yaml",
    "docs/*.pdf",
]
